### ISSUE TITLE
Setup AWS EC2 Instances

### ISSUE THREAD

**Issue by mt85** [mt85/IT490-Determination#1]
Create an Instance for App, DB, API, and MQ.
Install the necessary software on each machine.
Make sure you have the sample code working.
Refer to the below videos for help.
[Setup Intro](https://njit.instructure.com/courses/11946/pages/recording-it490-setup-intro-00-11)
[Setup EC2](https://njit.instructure.com/courses/11946/pages/recording-it490-setup-aws-ec2-04-52)
[Sample Code](https://njit.instructure.com/courses/11946/pages/recording-it490-setup-sample-code-14-01)
[App Structure Diagram](https://njit.instructure.com/courses/11946/pages/application-structure)

**Comment by smc58** [comment]
Completed.
I finished this while working for my previous group.

**Comment by mt85** [comment]
Can you add a screenshot of your ec2 instance list?
I'll be asking everyone for the screenshot.

Basically just the list that you see me enable during class.

**Comment by smc58** [comment]
[Screenshot of EC2 Instances.docx](https://github.com/mt85/IT490-Determination/files/4894087/Screenshot.of.EC2.Instances.docx)

**Comment by mt85** [comment]
Missing API VM, just an FYI but looks good otherwise.

**Comment by mkc24** [comment]
![Screenshot (379)](https://user-images.githubusercontent.com/60664916/87117257-15f37f00-c246-11ea-9064-2fc8cc42949f.png)

**Comment by ha382** [comment]
Screenshot of EC2 Instances. 
<img width="985" alt="Screen Shot 2020-07-13 at 12 41 31 PM" src="https://user-images.githubusercontent.com/55151467/87330469-9ea04280-c506-11ea-993a-906762f4aac3.png">
](url)

**Comment by mt85** [comment]
Looks like everyone is setup, closing the issue.
