### ISSUE TITLE
Create User DB Table

### ISSUE THREAD

**Issue by mt85** [mt85/IT490-Determination#8]
Create the table for the DB VM so it can store user details.

Should at the minimum have a primary key ID, email field, and a password field varchar(60).
Should also have a field for role (Client, Manager, Admin are the only valid options)

**Comment by smc58** [comment]
Completed
![image](https://user-images.githubusercontent.com/16457688/88475658-0a6bad80-cf00-11ea-8ceb-a982a68431d7.png)

**Comment by mt85** [comment]
Looks good, crazy long email field but it's ok. Just an FYI, in the future you may want to record created and modified dates, but this can be accomplished by "alter table" statements.
